language: java
install: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -DexternConfigRoot=pipelines/config -B -V"
script: "mvn cobertura:cobertura -DexternConfigRoot=pipelines/config"

after_success:
  - bash <(curl -s https://codecov.io/bash)