{
 "title": "Wuzeln",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nickname",
    "label": "player",
    "query": "SELECT p.nickname  FROM wuzeln.person p  JOIN wuzeln.useraccount u ON p.useraccount_id = u.id  JOIN wuzeln.useraccount_role ur ON u.id = ur.useraccount_id JOIN wuzeln.role r ON r.id = ur.roles_id WHERE r.name = 'ACTIVE_USER'"
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nr. of Matches",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"value\",\n  createddate AS \"time\" \nFROM wuzeln.person pe \n  JOIN wuzeln.player p ON p.person_id = pe.id\n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\nWHERE\n  $__timeFilter(m.createddate) \n  AND m.enddate is not null\n  AND pe.nickname IN ( $nickname )\nGROUP BY m.id"
    }
   ]
  },
  {
   "title": "Victories by Color",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \r\nnow() as time,\r\n  t.color, \r\n  count(distinct(m.id))\r\nFROM wuzeln.person pe \r\n  JOIN wuzeln.player p ON p.person_id = pe.id\r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE m.enddate IS NOT NULL \r\n  AND t.winner \r\n  AND $__timeFilter(m.createddate)\r\n  AND pe.nickname IN ( $nickname )\r\nGROUP BY t.color"
    }
   ]
  },
  {
   "title": "Won Matches",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "WITH winner_count as (\r\nSELECT\r\n count(m.id) AS \"value\",\r\n  pe.nickname AS nickname\r\nFROM wuzeln.person pe \r\n  JOIN wuzeln.player p ON p.person_id = pe.id\r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE\r\n  $__timeFilter(m.createddate) AND\r\n   m.enddate is not null AND\r\n  t.winner = TRUE\r\nGROUP BY pe.nickname\r\n  ), \r\nall_count as (\r\nSELECT\r\n count(m.id) AS \"value\",\r\n  pe.nickname AS nickname\r\nFROM wuzeln.person pe \r\n  JOIN wuzeln.player p ON p.person_id = pe.id\r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE\r\n  $__timeFilter(m.createddate) AND\r\n   m.enddate is not null\r\nGROUP BY pe.nickname\r\n  )\r\n  \r\nSELECT wc.value / cast(ac.value as float) as value, \r\nac.nickname as metric,\r\nnow() as time\r\nFROM winner_count wc \r\nJOIN all_count ac ON wc.nickname = ac.nickname\r\nAND wc.nickname IN ( $nickname )\r\nORDER BY value DESC\r\n"
    }
   ]
  },
  {
   "title": "Won Matches",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "WITH winner_count as (\r\nSELECT\r\n count(m.id) AS \"value\",\r\n  pe.nickname AS nickname\r\nFROM wuzeln.person pe \r\n  JOIN wuzeln.player p ON p.person_id = pe.id\r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE\r\n  $__timeFilter(m.createddate) AND\r\n   m.enddate is not null AND\r\n  t.winner = TRUE\r\nGROUP BY pe.nickname\r\n  ), \r\nall_count as (\r\nSELECT\r\n count(m.id) AS \"value\",\r\n  pe.nickname AS nickname\r\nFROM wuzeln.person pe \r\n  JOIN wuzeln.player p ON p.person_id = pe.id\r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE\r\n  $__timeFilter(m.createddate) AND\r\n   m.enddate is not null\r\nGROUP BY pe.nickname\r\n  )\r\n  \r\nSELECT \r\nac.nickname as name,\r\n(wc.value / cast(ac.value as float))*100 as value,\r\nac.value as \"nr. of played\",\r\nwc.value as \"nr. of won\"\r\nFROM winner_count wc \r\nJOIN all_count ac ON wc.nickname = ac.nickname\r\nWHERE wc.nickname IN ( $nickname )\r\nORDER BY value DESC\r\n"
    }
   ]
  },
  {
   "title": "Goals Shot (from Position)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() as time,\n  g.position, \n  count(*)\nFROM wuzeln.goal g\n  JOIN wuzeln.player pl ON g.player_id = pl.id \n  JOIN wuzeln.person pe ON pl.person_id = pe.id\nWHERE $__timeFilter(g.date) \n  AND pe.nickname IN( $nickname )\nGROUP BY g.position\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "With Andi in Team",
   "type": "graph",
   "description": "Percentage of matches played with Andi  in the same team. Taking into consideration only matches where Andi played.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "WITH \r\nmatches_with_andi AS (\r\nSELECT distinct(m.*)\r\nFROM wuzeln.person pe \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN wuzeln.match m on t.match_id = m.id\r\nWHERE pe.nickname = 'Andi' AND\r\n $__timeFilter(m.createddate) AND\r\n   m.enddate is not null\r\n),\r\nwith_andi AS (\r\nSELECT pe.nickname, count(*) as count\r\nFROM wuzeln.person pe \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN wuzeln.player pl2 ON pl2.team_id = t.id\r\nJOIN wuzeln.person pe2 ON pl2.person_id = pe2.id\r\nJOIN matches_with_andi m on m.id = t.match_id\r\nWHERE pe2.nickname = 'Andi'\r\nGROUP BY pe.nickname\r\nORDER BY count desc)\r\n\r\nSELECT\r\nwa.nickname as metric, \r\nTRUNC((cast(wa.count as decimal) / count(*))* 100, 2) as value,\r\nnow() as time\r\nFROM with_andi wa\r\nJOIN wuzeln.person pe ON wa.nickname = pe.nickname \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN matches_with_andi m on m.id = t.match_id\r\nWHERE pe.nickname IN ( $nickname )\r\nGROUP BY wa.nickname, wa.count, pe.nickname\r\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "With Andi in Team",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "WITH \r\nmatches_with_andi AS (\r\nSELECT distinct(m.*)\r\nFROM wuzeln.person pe \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN wuzeln.match m on t.match_id = m.id\r\nWHERE pe.nickname = 'Andi' AND\r\n $__timeFilter(m.createddate) AND\r\n   m.enddate is not null\r\n),\r\nwith_andi AS (\r\nSELECT pe.nickname, count(*) as count\r\nFROM wuzeln.person pe \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN wuzeln.player pl2 ON pl2.team_id = t.id\r\nJOIN wuzeln.person pe2 ON pl2.person_id = pe2.id\r\nJOIN matches_with_andi m on m.id = t.match_id\r\nWHERE pe2.nickname = 'Andi'\r\nGROUP BY pe.nickname\r\nORDER BY count desc)\r\n\r\nSELECT\r\nwa.nickname as metric, \r\nTRUNC((cast(wa.count as decimal) / count(*))* 100, 2) as value,\r\nwa.count as with_andi, count(*) as all_played\r\nFROM with_andi wa\r\nJOIN wuzeln.person pe ON wa.nickname = pe.nickname \r\nJOIN wuzeln.player pl ON pe.id = pl.person_id\r\nJOIN wuzeln.team t ON pl.team_id = t.id\r\nJOIN matches_with_andi m on m.id = t.match_id\r\nWHERE pe.nickname IN ( $nickname )\r\nGROUP BY wa.nickname, wa.count, pe.nickname\r\nORDER BY value desc"
    }
   ]
  },
  { "title": "Offensive & Defensive Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Offensive Score over Time (Grouped by Month)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(sp.scoreoffensive),\n  date_trunc('month', m.createddate) as \"time\",\n  pe.nickname as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname IN ( $nickname )\nGROUP BY pe.nickname, time\nORDER BY pe.nickname, time"
    }
   ]
  },
  {
   "title": "Defensive Score over Time (Grouped by Month)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(sp.scoredefensive),\n  date_trunc('month', m.createddate) as \"time\",\n  pe.nickname as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname IN ( $nickname )\nGROUP BY pe.nickname, time\nORDER BY pe.nickname, time"
    }
   ]
  },
  {
   "title": "Offensive Score Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  sp.scoreoffensive,\n  m.startdate as \"time\"\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n   AND pe.nickname IN ( $nickname )\n"
    }
   ]
  },
  {
   "title": "Defensive Score Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  sp.scoredefensive,\n  m.startdate as \"time\"\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname IN ( $nickname )"
    }
   ]
  },
  { "title": "Match Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Match Quality",
   "type": "table",
   "description": "Score is computed as: looser_goals / winner_goals.\nQuality is normalized to: min=0, max=0.9",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT \nm.method as method , \navg( ((cast(sm.looserscore as double precision )/ sm.winnerscore)/0.9)*100) as \"avg quality\",\navg( cast(sm.looserscore as double precision )/ sm.winnerscore) as \"avg score\",\ncount(m) as matches\nFROM wuzeln.stats_match sm\nJOIN wuzeln.match m ON m.id = sm.match_id\nWHERE $__timeFilter(m.createddate)\nGROUP BY method\n"
    }
   ]
  },
  {
   "title": "Match Quality over Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 50 },
   "yaxes": [
    { "format": "percent", "label": "Quality" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \nm.method as metric , \navg( ((cast(sm.looserscore as double precision )/ sm.winnerscore)/0.9)*100) as value,\n date_trunc('month', m.createddate) as time\nFROM wuzeln.stats_match sm\nJOIN wuzeln.match m ON m.id = sm.match_id\nWHERE $__timeFilter(m.createddate)\nGROUP BY metric, time\nORDER BY time\n"
    },
    {
     "rawSql": "SELECT \n(m.method || '_COUNT') as metric , \ncount(m) as value,\n date_trunc('month', m.createddate) as time\nFROM wuzeln.stats_match sm\nJOIN wuzeln.match m ON m.id = sm.match_id\nWHERE $__timeFilter(m.createddate)\nGROUP BY metric, time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Match Quality",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \nm.method as metric , \navg( ((cast(sm.looserscore as double precision )/ sm.winnerscore)/0.9)*100) as value,\nnow() as time\nFROM wuzeln.stats_match sm\nJOIN wuzeln.match m ON m.id = sm.match_id\nGROUP BY metric\n"
    }
   ]
  },
  { "title": "Matches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Nr. of Matches (per Week)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   count(distinct(m.id)),\n   date_trunc('week', m.createddate) as \"time\"\nFROM wuzeln.person pe \n  JOIN wuzeln.player p ON p.person_id = pe.id\n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\nWHERE\n  $__timeFilter(m.createddate) \n  AND m.enddate is not null\n  AND pe.nickname IN ( $nickname )\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Nr. of Matches (per Month)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n   count(distinct(m.id)),\n   date_trunc('month', m.createddate) as \"time\"\nFROM wuzeln.person pe \n  JOIN wuzeln.player p ON p.person_id = pe.id\n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\nWHERE\n  $__timeFilter(m.createddate) \n  AND m.enddate is not null\n  AND pe.nickname IN ( $nickname )\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Distribution of Match Length (min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "rawSql": "select DISTINCT\r\nEXTRACT(epoch FROM m.enddate - m.startdate)/60,\r\nm.startdate as \"time\"\r\nfrom wuzeln.player p \r\n  JOIN wuzeln.team t on t.id = p.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\n  JOIN wuzeln.person pe ON p.person_id = pe.id\r\nwhere m.enddate is not null \r\nAND $__timeFilter(m.startdate)\r\nAND pe.nickname IN ( $nickname )"
    }
   ]
  }
 ]
}