{
 "title": "Wuzeln - Individual",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nickname",
    "label": "player",
    "query": "SELECT p.nickname  FROM wuzeln.person p  JOIN wuzeln.useraccount u ON p.useraccount_id = u.id  JOIN wuzeln.useraccount_role ur ON u.id = ur.useraccount_id JOIN wuzeln.role r ON r.id = ur.roles_id WHERE r.name = 'ACTIVE_USER'"
   }
  ]
 },
 "panels": [
  {
   "title": "Scores over Time (Grouped by Week)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(sp.scoreoffensive),\n  date_trunc('week', m.createddate) as \"time\",\n   'Offensive' as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname = '$nickname' \nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  avg(sp.scoredefensive),\n  date_trunc('week', m.createddate) as \"time\",\n  'Defensive' as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname = '$nickname' \nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Scores over Time (Grouped by Month)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  avg(sp.scoredefensive),\n  date_trunc('month', m.createddate) as \"time\",\n  'Defensive' as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname = '$nickname'\nGROUP BY time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  avg(sp.scoreoffensive),\n  date_trunc('month', m.createddate) as \"time\",\n   'Offensive' as metric\nFROM\n  wuzeln.stats_player sp \n  JOIN wuzeln.player p on sp.player_id = p.id \n  JOIN wuzeln.team t on t.id = p.team_id\n  JOIN wuzeln.match m on m.id = t.match_id\n  JOIN wuzeln.person pe ON p.person_id = pe.id\nWHERE\n  $__timeFilter(m.createddate)\n  AND pe.nickname = '$nickname'\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Prey",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \r\n  goaliePerson.nickname,\r\n  now() as time,\r\n  count(*) as count\r\nFROM wuzeln.goal g\r\n  JOIN wuzeln.player goalie ON g.goalie_id = goalie.id\r\n  JOIN wuzeln.player kicker ON g.player_id = kicker.id\r\n  JOIN wuzeln.person goaliePerson ON goalie.person_id = goaliePerson.id\r\n  JOIN wuzeln.person kickerPerson ON kicker.person_id = kickerPerson.id\r\n  JOIN wuzeln.team t on t.id = kicker.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE m.enddate IS NOT NULL \r\n  AND $__timeFilter(m.createddate)\r\n  AND kickerPerson.nickname = '$nickname'\r\nGROUP BY goaliePerson.nickname\r\nORDER BY count"
    }
   ]
  },
  {
   "title": "Nemesis",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT \r\n  kickerPerson.nickname,\r\n  now() as time,\r\n  count(*) as count\r\nFROM wuzeln.goal g\r\n  JOIN wuzeln.player goalie ON g.goalie_id = goalie.id\r\n  JOIN wuzeln.player kicker ON g.player_id = kicker.id\r\n  JOIN wuzeln.person goaliePerson ON goalie.person_id = goaliePerson.id\r\n  JOIN wuzeln.person kickerPerson ON kicker.person_id = kickerPerson.id\r\n  JOIN wuzeln.team t on t.id = kicker.team_id\r\n  JOIN wuzeln.match m on m.id = t.match_id\r\nWHERE m.enddate IS NOT NULL \r\n  AND $__timeFilter(m.createddate)\r\n  AND goaliePerson.nickname = '$nickname'\r\nGROUP BY kickerPerson.nickname\r\nORDER BY count"
    }
   ]
  },
  {
   "title": "Goals Shot (from Position)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() as time,\n  g.position, \n  count(*)\nFROM wuzeln.goal g\n  JOIN wuzeln.player pl ON g.player_id = pl.id \n  JOIN wuzeln.person pe ON pl.person_id = pe.id\nWHERE $__timeFilter(g.date) \n  AND pe.nickname = '$nickname' \nGROUP BY g.position\n"
    }
   ]
  },
  {
   "title": "Goals Received (from Position)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \nnow() as time,\n  g.position, \n  count(*)\nFROM wuzeln.goal g\n  JOIN wuzeln.player pl ON g.goalie_id = pl.id \n  JOIN wuzeln.person pe ON pl.person_id = pe.id\nWHERE $__timeFilter(g.date) \n  AND pe.nickname = '$nickname'\nGROUP BY g.position\n"
    }
   ]
  }
 ]
}