GRANT USAGE ON SCHEMA wuzeln TO grafana;
GRANT SELECT ON wuzeln.team TO grafana;
GRANT SELECT ON wuzeln.useraccount_role TO grafana;
GRANT SELECT ON wuzeln.role TO grafana;
GRANT SELECT ON wuzeln.registration_person TO grafana;
GRANT SELECT ON wuzeln.registration TO grafana;
GRANT SELECT ON wuzeln.person_match TO grafana;
GRANT SELECT ON wuzeln.goal TO grafana;
GRANT SELECT ON wuzeln.player TO grafana;
GRANT SELECT ON wuzeln.person TO grafana;
GRANT SELECT ON wuzeln.match TO grafana;
GRANT SELECT ON wuzeln.useraccount TO grafana;
GRANT SELECT ON wuzeln.stats_player TO grafana;